spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/myseries?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: dd
    password: password